<!DOCTYPE html>
<html>
<head>
	<title>Exercise 2</title>
</head>
<body>

<?php

$data = array (
  'accessLevel' => 'public',
  'accrualPeriodicity' => 'Continuously updated',
  'bureauCode' => 
  array (
    0 => '005:15',
  ),
  'contactPoint' => 'ASB Secretary',
  'dataDictionary' => 'http://www.agcensus.usda.gov/Publications/2007/Full_Report/Volume_1,_Chapter_1_US/usappxb.pdf',
  'dataQuality' => true,
  'description' => 'Quick Stats API is the programmatic interface to the National Agricultural Statistics Service\'s (NASS) online database containing results from the 1997, 2002, 2007, and 2012 Censuses of Agriculture as well as the best source of NASS survey published estimates. The census collects data on all commodities produced on U.S. farms and ranches, as well as detailed information on expenses, income, and operator characteristics. The surveys that NASS conducts collect information on virtually every facet of U.S. agricultural production.',
  'distribution' => 
  array (
    0 => 
    array (
      'accessURL' => 'http://quickstats.nass.usda.gov/api',
      'format' => 'application/json',
    ),
  ),
  'identifier' => 'USDA-NASS-00003',
  'issued' => '2014-05-02',
  'keyword' => 
  array (
    0 => 'African American operators',
    1 => 'Agriculture',
    2 => 'American Indian Reservation farms',
    3 => 'Asian operators',
    4 => 'Brussels sprouts',
    5 => 'CCC',
    6 => 'CRP',
    7 => 'Chinese cabbage',
    8 => 'Christmas trees',
    9 => 'Commodity Credit Corporation loans',
    10 => 'Conservation Reserve',
    11 => 'Data',
    12 => 'English walnuts',
    13 => 'Farmable Wetlands',
    14 => 'Hispanic operators',
    15 => 'Latino operators',
    16 => 'NAICS',
    17 => 'NASS',
    18 => 'North American Industry Classification System',
    19 => 'Pacific Island operators',
    20 => 'Spanish operators',
    21 => 'Temples',
    22 => 'USDA',
    23 => 'Valencia oranges',
    24 => 'Wetlands Reserve',
    25 => 'abandoned',
    26 => 'acres',
    27 => 'ag land',
    28 => 'ag services',
    29 => 'age',
    30 => 'agri-tourism',
    31 => 'agriculture',
    32 => 'alfalfa',
    33 => 'alfalfa seed',
    34 => 'almonds',
    35 => 'alpacas',
    36 => 'angora goats',
    37 => 'apples',
    38 => 'apricots',
    39 => 'aquaculture',
    40 => 'aquatic plants',
    41 => 'artichokes',
    42 => 'asparagus',
    43 => 'avocados',
    44 => 'bales',
    45 => 'bananas',
    46 => 'barley',
    47 => 'bedding plants',
    48 => 'bee colonies',
    49 => 'beef cow',
    50 => 'bees',
    51 => 'beets',
    52 => 'bell peppers',
    53 => 'berries',
    54 => 'bison',
    55 => 'black operators',
    56 => 'blackberries',
    57 => 'blackeyed peas',
    58 => 'blueberries',
    59 => 'boysenberries',
    60 => 'broccoli',
    61 => 'broilers',
    62 => 'bulbs',
    63 => 'bull',
    64 => 'burros',
    65 => 'bushels',
    66 => 'cabbage',
    67 => 'calves',
    68 => 'cantaloupes',
    69 => 'carrots',
    70 => 'cash rents',
    71 => 'cattle',
    72 => 'cauliflower',
    73 => 'celery',
    74 => 'chemicals',
    75 => 'cherries',
    76 => 'chestnuts',
    77 => 'chickens',
    78 => 'chicory',
    79 => 'chile',
    80 => 'citrus',
    81 => 'coffee',
    82 => 'collards',
    83 => 'combines',
    84 => 'conservation practices',
    85 => 'contract labor',
    86 => 'corms',
    87 => 'corn',
    88 => 'cotton',
    89 => 'cotton pickers',
    90 => 'cowpeas',
    91 => 'cranberries',
    92 => 'crop insurance',
    93 => 'cropland',
    94 => 'cucumbers',
    95 => 'currants',
    96 => 'custom hauling',
    97 => 'customwork',
    98 => 'cut flowers',
    99 => 'cuttings',
    100 => 'cwt',
    101 => 'daikon',
    102 => 'dairy products',
    103 => 'dates',
    104 => 'deer',
    105 => 'dewberries',
    106 => 'donkeys',
    107 => 'dry edible beans',
    108 => 'dry edible peas',
    109 => 'ducks',
    110 => 'durum wheat',
    111 => 'eggplant',
    112 => 'eggs',
    113 => 'elk',
    114 => 'emus',
    115 => 'endive',
    116 => 'equipment',
    117 => 'escarole',
    118 => 'ewe',
    119 => 'experimental farms',
    120 => 'farm demographics',
    121 => 'farm economics',
    122 => 'farm income',
    123 => 'farm operations',
    124 => 'farms',
    125 => 'feed purchased',
    126 => 'fertilizer',
    127 => 'fescue seed',
    128 => 'field crops',
    129 => 'figs',
    130 => 'filberts',
    131 => 'flaxseed',
    132 => 'floriculture',
    133 => 'flower seeds',
    134 => 'flowering plants',
    135 => 'foliage plants',
    136 => 'forage',
    137 => 'fruits',
    138 => 'fuels',
    139 => 'garden plants',
    140 => 'garlic',
    141 => 'geese',
    142 => 'ginseng',
    143 => 'goats',
    144 => 'government payments',
    145 => 'grapefruit',
    146 => 'grapes',
    147 => 'grass seed',
    148 => 'grazing',
    149 => 'green onions',
    150 => 'greenchop',
    151 => 'greenhouse',
    152 => 'greenhouse tomatoes',
    153 => 'greenhouse vegetables',
    154 => 'guavas',
    155 => 'harvested',
    156 => 'harvesters',
    157 => 'hay',
    158 => 'hay balers',
    159 => 'haylage',
    160 => 'hazelnuts',
    161 => 'herbs',
    162 => 'herd',
    163 => 'hired farm labor',
    164 => 'hogs',
    165 => 'honey',
    166 => 'honeydew melon',
    167 => 'hops',
    168 => 'horseradish',
    169 => 'horses',
    170 => 'idle',
    171 => 'institutional farms',
    172 => 'interest expense',
    173 => 'inventory',
    174 => 'irrigation',
    175 => 'kale',
    176 => 'kiwifruit',
    177 => 'kumquats',
    178 => 'lambs',
    179 => 'land in farms',
    180 => 'land rents',
    181 => 'land value',
    182 => 'landlord',
    183 => 'layers',
    184 => 'lemons',
    185 => 'lentils',
    186 => 'lettuce',
    187 => 'lima beans',
    188 => 'limes',
    189 => 'liners',
    190 => 'llamas',
    191 => 'loganberries',
    192 => 'macadamia nuts',
    193 => 'machinery value',
    194 => 'mangoes',
    195 => 'manure',
    196 => 'maple syrup',
    197 => 'meat goats',
    198 => 'melons',
    199 => 'milk cow',
    200 => 'milk goats',
    201 => 'mink',
    202 => 'mint',
    203 => 'mohair',
    204 => 'mules',
    205 => 'mushrooms',
    206 => 'mustard',
    207 => 'native Hawaiian operators',
    208 => 'nectarines',
    209 => 'noncitrus',
    210 => 'nonirrigated',
    211 => 'number sold',
    212 => 'nursery',
    213 => 'nursery stock',
    214 => 'nuts',
    215 => 'oats',
    216 => 'okra',
    217 => 'olives',
    218 => 'onions',
    219 => 'operation',
    220 => 'operator characteristics',
    221 => 'oranges',
    222 => 'orchards',
    223 => 'organic',
    224 => 'ostriches',
    225 => 'other animals',
    226 => 'papayas',
    227 => 'parsley',
    228 => 'passion fruit',
    229 => 'pasture',
    230 => 'peaches',
    231 => 'peanuts',
    232 => 'pears',
    233 => 'peas',
    234 => 'pecans',
    235 => 'pelts',
    236 => 'peppers',
    237 => 'persimmons',
    238 => 'pheasants',
    239 => 'pickles',
    240 => 'pigeons',
    241 => 'pigs',
    242 => 'pima cotton',
    243 => 'pineapples',
    244 => 'pistachios',
    245 => 'planted',
    246 => 'plugs',
    247 => 'plums',
    248 => 'pluots',
    249 => 'pomegranates',
    250 => 'ponies',
    251 => 'popcorn',
    252 => 'potatoes',
    253 => 'poultry',
    254 => 'pounds',
    255 => 'price',
    256 => 'primary occupation',
    257 => 'production contracts',
    258 => 'production expenses',
    259 => 'property tax',
    260 => 'proso millet',
    261 => 'prunes',
    262 => 'pullets',
    263 => 'pumpkins',
    264 => 'quail',
    265 => 'rabbits',
    266 => 'radishes',
    267 => 'rangeland',
    268 => 'raspberries',
    269 => 'real estate',
    270 => 'research farms',
    271 => 'rhizomes',
    272 => 'rhubarb',
    273 => 'rice',
    274 => 'ryegrass seed',
    275 => 'safflower',
    276 => 'sales',
    277 => 'seedlings',
    278 => 'sheep',
    279 => 'short rotation',
    280 => 'silage',
    281 => 'snap beans',
    282 => 'sod',
    283 => 'sorghum',
    284 => 'soybeans',
    285 => 'spinach',
    286 => 'spring wheat',
    287 => 'squab',
    288 => 'squash',
    289 => 'storage capacity',
    290 => 'strawberries',
    291 => 'sugar',
    292 => 'sugarbeets',
    293 => 'sugarcane',
    294 => 'sunflower seed',
    295 => 'sweet cherries',
    296 => 'sweet corn',
    297 => 'sweet potatoes',
    298 => 'tame blueberries',
    299 => 'tame hay',
    300 => 'tangelos',
    301 => 'tangerines',
    302 => 'tart cherries',
    303 => 'tenant',
    304 => 'tenure',
    305 => 'tobacco',
    306 => 'tomatoes',
    307 => 'tons',
    308 => 'tractors',
    309 => 'trucks',
    310 => 'tubers',
    311 => 'turkeys',
    312 => 'turnip greens',
    313 => 'turnips',
    314 => 'upland cotton',
    315 => 'utilities',
    316 => 'value of production',
    317 => 'vegetable seeds',
    318 => 'vegetables',
    319 => 'vines',
    320 => 'walnuts',
    321 => 'watercress',
    322 => 'watermelons',
    323 => 'wheat',
    324 => 'white operators',
    325 => 'wild blueberries',
    326 => 'wild hay',
    327 => 'winter wheat',
    328 => 'women operators',
    329 => 'woodland',
    330 => 'woody crops',
    331 => 'wool',
  ),
  'landingPage' => 'http://www.nass.usda.gov/Quick_Stats/',
  'license' => 'Creative Commons Attribution',
  'mbox' => 'nass@nass.usda.gov',
  'modified' => '2014-05-16T19:45:56.688933',
  'notes' => 'Quick Stats API is the programmatic interface to the National Agricultural Statistics Service\'s (NASS) online database containing results from the 1997, 2002, 2007, and 2012 Censuses of Agriculture as well as the best source of NASS survey published estimates. The census collects data on all commodities produced on U.S. farms and ranches, as well as detailed information on expenses, income, and operator characteristics. The surveys that NASS conducts collect information on virtually every facet of U.S. agricultural production.',
  'programCode' => 
  array (
    0 => '005:042',
  ),
  'publisher' => 'National Agricultural Statistics Service, Department of Agriculture',
  'references' => 
  array (
    0 => 'http://www.nass.usda.gov/Education_and_Outreach/Understanding_Statistics/index.asp',
    1 => 'http://www.nass.usda.gov/Surveys/Guide_to_NASS_Surveys/Census_of_Agriculture/index.asp',
  ),
  'spatial' => 'United States',
  'theme' => 
  array (
    0 => 'Agriculture',
    1 => 'Weather',
    2 => 'Climate',
    3 => 'Research',
  ),
  'title' => 'Quick Stats Agricultural Database API',
);


// your code goes here
$keywords = $data['keyword'];
echo '<ul>';
foreach ($keywords as $keyword) {
	if ($keyword == 'pickles') {
		echo '<li style="font-size:80px; color:green; text-transform:uppercase;">'.$keyword.'</li>';
	}
	else {
		echo '<li>'.$keyword.'</li>';
	}
}
echo '</ul>';
?>

</body>
</html>